# Generated by Django 5.0.6 on 2024-06-25 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['profile_name'], name='account_pro_profile_203349_idx'),
        ),
    ]
