# Generated by Django 5.0.6 on 2024-06-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_status',
            field=models.CharField(choices=[('AD', 'ADMIN'), ('MD', 'MODERATOR'), ('US', 'USER')], default='USER'),
        ),
    ]
