# Generated by Django 5.0.6 on 2024-06-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admin_status',
            field=models.CharField(choices=[('AD', 'ADMIN'), ('MD', 'MODERATOR'), ('US', 'USER')], default='US', max_length=2),
        ),
    ]
