# Generated by Django 5.0.6 on 2024-06-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='reciprocity',
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
