# Generated by Django 5.0.6 on 2024-06-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0003_alter_file_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='file_processing.project'),
        ),
        migrations.AlterField(
            model_name='file',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='file_processing.project'),
        ),
    ]
