# Generated by Django 5.0.6 on 2024-06-26 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0007_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FileExtensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=5)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext', to='file_processing.programminglanguages')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='extensions',
            field=models.ManyToManyField(related_name='project', to='file_processing.programminglanguages'),
        ),
    ]
