# Generated by Django 5.0.6 on 2024-06-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0008_programminglanguages_fileextensions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='extensions',
            new_name='languages',
        ),
    ]
