# Generated by Django 5.0.6 on 2024-06-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0009_rename_extensions_project_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filling_the_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='project', to='file_processing.programminglanguages'),
        ),
    ]
