# Generated by Django 5.0.6 on 2024-06-29 13:00

import file_processing.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0011_file_extension_id_alter_file_filling_the_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filling_the_file',
            field=models.FileField(upload_to=file_processing.utils.project_directory_path),
        ),
    ]
