# Generated by Django 5.0.6 on 2024-07-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0013_file_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uuid',
        ),
    ]
